### ISSUE TITLE
Reset history

### ISSUE THREAD

**Issue by deads2k** [kubernetes-incubator/kube-mesos-framework#21]
I think we should consider resetting the history on this project.  We started as a straight clone to ease the transition, but now that we've transitioned to a more permanent structure, there isn't a whole lot of benefit to keeping history on all of vendor as a for instance.

Keeping the old history is hiding the real actors in this repo from people searching through.

@k82cn, what do you think?

**Comment by philips** [comment]
can you filter-branch out nearly everything?

**Comment by deads2k** [comment]
> can you filter-branch out nearly everything?

The only way I know to do that is to start over from kube/kube.  Knowing the end state I could use filter-branch --subdirectory-filter and then copy th ecurrent state of the repo over and force push.

Is there a cleaner way?

**Comment by philips** [comment]
Not that I know of.

**Comment by deads2k** [comment]
@k82cn I'm inclined to do this tomorrow to help with the ability to inspect the project.  I'll save history on stuff from contrib/mesos

**Comment by k82cn** [comment]
Agree with you to clear up the history :). Thanks very much.

**Comment by deads2k** [comment]
Alright, here goes.  There's no way to do this other than a force push.  I've created a branch here: https://github.com/kubernetes-incubator/kube-mesos-framework/tree/unfiltered-history which I think will survive the push, but which we should remove when we're sure we're happy with the new history.

**Comment by deads2k** [comment]
I think it worked and the result looks a lot cleaner.
