### ISSUE TITLE
Point docs to kube-mesos-framework

### ISSUE THREAD

**Issue by deads2k** [kubernetes-incubator/kube-mesos-framework#4]
Need to update http://kubernetes.io/docs/getting-started-guides/mesos/ to point to this repo

**Comment by k82cn** [comment]
@deads2k , suggest to update it when this repo is cleaned up; otherwise, the user/developer maybe confused.

**Comment by deads2k** [comment]
> @deads2k , suggest to update it when this repo is cleaned up; otherwise, the user/developer maybe confused.

I want to get the packages fixed, but after that I think this is ready to go live.

**Comment by deads2k** [comment]
Fixed by https://github.com/kubernetes/kubernetes.github.io/pull/1339
