### ISSUE TITLE
[e2e] Update docker version in Mesos Slave container.

### ISSUE THREAD

**Issue by k82cn** [kubernetes-incubator/kube-mesos-framework#43]
**FOUND IN VERSION** (Details about the version, e.g. 0.7. Please list the other versions which this bug exist.)
[ 0.7 ]

**PLATFORMS e.g. 'uname -a'**:
[ `Linux dcosdemo02.eng.platformlab.ibm.com 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux` ]

**COMMANDS OR DAEMONS**: -- list all related components
[ e2e ]

**DESCRIPTION**: -- symptom of the problem a customer would see
[
```
I1015 00:52:58.545079     196 kubelet.go:2261] skipping pod synchronization - [container runtime is down]
E1015 00:52:58.565074     196 kubelet.go:2651] Container runtime sanity check failed: container runtime version is older than 1.21
I1015 00:53:03.545400     196 kubelet.go:2261] skipping pod synchronization - [container runtime is down]
E1015 00:53:03.565996     196 kubelet.go:2651] Container runtime sanity check failed: container runtime version is older than 1.21
E1015 00:53:04.622051     196 kubelet.go:2192] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
```
]

**IMPACT**: -- impact of problem in customer env (best/worse case scenarios)
[ Can not run e2e test. ]

**EXPECTED BEHAVIOR**:
[ ]

**HOW TO REPRODUCE/DETAILS OF PROBLEM**: -- full details of the problem
[ ]

**Comment by k82cn** [comment]
I'm going to fork from https://github.com/mesosphere/mesos-slave-dind and update docker version accordingly.

**Comment by fangli1211** [comment]
hi,mada.I found a problem on buliding .
 vendor/github.com/google/certificate-transparency/go/x509/x509.go:1461: undefined: elliptic.P224
 make: *** [all] Error 1
Can you help me to solve this problem?

**Comment by k82cn** [comment]
@fangli1211 , can help to open a new issue for the build error? with go version & OS info :).

**Comment by fangli1211** [comment]
@k82cn OK
