### ISSUE TITLE
[docs] Link to getting started guides is broken on README.md

### ISSUE THREAD

**Issue by tobilg** [kubernetes-incubator/kube-mesos-framework#47]
**FOUND IN VERSION** (Details about the version, e.g. 0.7. Please list the other versions which this bug exist.)
[current master ]

**PLATFORMS e.g. 'uname -a'**:
[na ]

**COMMANDS OR DAEMONS**: -- list all related components
[na]

**DESCRIPTION**: -- symptom of the problem a customer would see
The link to the getting started guides in the root README.md is currently broken. https://github.com/kubernetes-incubator/kube-mesos-framework/docs/getting-started-guides/mesos.md yields a 404, but I'm unsure where the actual link should point to. That's why I didn't submit a PR.

**IMPACT**: -- impact of problem in customer env (best/worse case scenarios)
The getting started guides cannot be accessed directly.

**EXPECTED BEHAVIOR**:
The link works.

**HOW TO REPRODUCE/DETAILS OF PROBLEM**: -- full details of the problem
Check the link in the README.md

**Comment by tobilg** [comment]
Furthermore, the link to the architecture is a 404 as well: https://github.com/kubernetes-incubator/kube-mesos-framework/blob/master/docs/architecture.md

**Comment by tobilg** [comment]
Thanks for the fix!

**Comment by k82cn** [comment]
My pleasure :). Please feel free to open the issue if any.
