### ISSUE TITLE
Wire up travis

### ISSUE THREAD

**Issue by deads2k** [kubernetes-incubator/kube-mesos-framework#5]
We should wire up travis on pulls to test them

**Comment by k82cn** [comment]
@deads2k , do you mean CI?

**Comment by deads2k** [comment]
> @deads2k , do you mean CI?

Yes, but you can start very basic: does it build.

**Comment by deads2k** [comment]
I was thinking about Travis in particular: https://travis-ci.org.  There ought to be help available there for setting it up.  Remember to avoid grant it to much authority with your GitHub credentials.

Starting with build, then adding gofmt, and unit tests is probably the best plan.

**Comment by k82cn** [comment]
The build was updated at: https://travis-ci.org/kubernetes-incubator/kube-mesos-framework

Is there anyway to broadcast to all collaborator in this repo?

**Comment by deads2k** [comment]
> Is there anyway to broadcast to all collaborator in this repo?

Not that I know, but awesome!  You think we're ready to start forcing green test for merge and protect the master branch?

**Comment by deads2k** [comment]
> Not that I know, but awesome! You think we're ready to start forcing green test for merge and protect the master branch?

I turned on branch protection, but as an admin, you'll have the power to merge despite the check.  The button shows up red.

**Comment by k82cn** [comment]
>I turned on branch protection, but as an admin, you'll have the power to merge despite the check. The button shows up red.

Got that, I'll also try to follow the process to use branch when CI/code is stable.

**Comment by k82cn** [comment]
Close this issue for now, as the CI is running for days. Will enable e2e test in #32 .
