### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by TracyBin** [kubernetes-incubator/kube-mesos-framework#63]
**FOUND IN VERSION** (Details about the version, e.g. 0.7. Please list the other versions which this bug exist.)
[ 0.8]

**PLATFORMS e.g. 'uname -a'**:
[[root@centos-node-1 kube-mesos-framework-release-0.8]# uname -a
Linux centos-node-1 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@centos-node-1 kube-mesos-framework-release-0.8]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) ]

**COMMANDS OR DAEMONS**: -- list all related components
[make release ]

**DESCRIPTION**: -- symptom of the problem a customer would see
[[root@centos-node-1 kube-mesos-framework-release-0.8]# make release
+++ [0207 14:57:52] Verifying Prerequisites....
+++ [0207 14:57:55] Building Docker image kube-build:build-bab9018bcb
+++ Docker build command failed for kube-build:build-bab9018bcb

Sending build context to Docker daemon 15.92 MB
Step 1/11 : FROM gcr.io/google_containers/kube-cross:v1.6.3-7
 ---> 33fe81337964
Step 2/11 : RUN touch /kube-build-image
 ---> Using cache
 ---> 2fe7b5c8972f
Step 3/11 : RUN chmod -R a+rwx /usr/local/go/pkg ${K8S_PATCHED_GOROOT}/pkg
 ---> Running in b0c49e972463
chmod: cannot access '/pkg': No such file or directory
The command '/bin/sh -c chmod -R a+rwx /usr/local/go/pkg ${K8S_PATCHED_GOROOT}/pkg' returned a non-zero code: 1

To retry manually, run:

docker build -t kube-build:build-bab9018bcb --pull=false /root/mesos+k8s/kubernetes/kube-mesos-framework-release-0.8/_output/images/kube-build:build-bab9018bcb ]

**IMPACT**: -- impact of problem in customer env (best/worse case scenarios)
[ ]

**EXPECTED BEHAVIOR**:
[ ]

**HOW TO REPRODUCE/DETAILS OF PROBLEM**: -- full details of the problem
[ ]

**Comment by TracyBin** [comment]
It seems like a lack of configuration,but i edit Dockerfile and modify ${K8S_PATCHED_GOROOT},other error occured.
pkg/scheduler/components/scheduler.go:25:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/backoff" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/backoff (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/backoff (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/backoff (from $GOPATH)
pkg/scheduler/service/service.go:51:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/election" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/election (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/election (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/election (from $GOPATH)
pkg/scheduler/service/service.go:53:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/flagutil" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/flagutil (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/flagutil (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/flagutil (from $GOPATH)
cmd/k8sm-scheduler/main.go:23:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/hyperkube" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/hyperkube (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/hyperkube (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/hyperkube (from $GOPATH)
pkg/scheduler/service/service.go:55:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/minion/config" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/minion/config (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/minion/config (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/minion/config (from $GOPATH)
pkg/scheduler/executorinfo/registry.go:25:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/node" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/node (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/node (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/node (from $GOPATH)
pkg/scheduler/components/scheduler.go:26:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/offers" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/offers (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/offers (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/offers (from $GOPATH)
pkg/scheduler/components/framework/framework.go:31:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/offers/metrics" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/offers/metrics (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/offers/metrics (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/offers/metrics (from $GOPATH)
pkg/scheduler/service/service.go:56:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/podutil" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/podutil (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/podutil (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/podutil (from $GOPATH)
pkg/scheduler/components/framework/framework.go:32:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/proc" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/proc (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/proc (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/proc (from $GOPATH)
pkg/scheduler/service/service.go:57:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/profile" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/profile (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/profile (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/profile (from $GOPATH)
pkg/scheduler/components/podstoreadapter.go:20:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/queue" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/queue (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/queue (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/queue (from $GOPATH)
pkg/scheduler/service/service.go:58:2: cannot find package "github.com/kubernetes-incubator/kube-mesos-framework/pkg/runtime" in any of:
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/vendor/github.com/kubernetes-incubator/kube-mesos-framework/pkg/runtime (vendor tree)
	/usr/local/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/runtime (from $GOROOT)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/kubernetes-incubator/kube-mesos-framework/pkg/runtime (from $GOPATH)
Makefile:79: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:176: recipe for target 'cross' failed
make: *** [cross] Error 1
make: *** [release] 错误 1

**Comment by k82cn** [comment]
which branch are you using? 0.8 is a working branch.

**Comment by TracyBin** [comment]
It's all right now when use make command instead of make release
